server.port=8081
spring.application.name=notification-service

# For my testing I used two brokers. On first request Producer does not know which broker is Leader
# From subsequent requests this line will not be executed, bcz after first request PRODUCER will cache
# the metadata which will tell PRODUCER - which broker is leader for specific topic's specific partition
spring.kafka.bootstrap-servers=localhost:9092,localhost:9192

spring.kafka.producer.properties.metadata.max.age.ms=300000

spring.kafka.producer.acks=all

#----------------- STAGE 1: SERIALIZER -----------
#1.For KEY
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

#2. For VALUE : JsonSerializer,auto-converts Java objects to JSON bytes
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


#---------- STAGE 2: RECORD ACCUMULATOR ----------
# 2.1) Batching, wait for 20ms to collect more messages before sending
spring.kafka.producer.properties.linger.ms=20

#2.2) Max batch size, send when batch reaches 32KB (even if linger.ms hasn't expired)
spring.kafka.producer.properties.batch.size=32768


#---------- STAGE 3: COMPRESSION ------------
spring.kafka.producer.properties.compression.type=snappy